spring:
  datasource:
     driverClassName: com.mysql.jdbc.Driver
     url: jdbc:mysql://localhost:3306/SweetPeaTimes
     username: root
     password: Fah@232538
#     jpa:
#        hibernate.ddl-auto: update
#        generate-ddl: true
#        show-swl: true
#        hibernate:
#           naming:
#               physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#               implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
